apiVersion: v1
kind: Service
metadata:
  name: alert-service
  namespace: api-analytics
spec:
  selector:
    app: alert-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: ClusterIP
